URL_SERVICE = 'https://0fcae563-bc1a-4e5f-90cb-63c815c52954.serverhub.praktikum-services.ru'
DOC_PATH = '/docs/'
LOG_MAIN_PATH = '/api/logs/main/'
USERS_TABLE_PATH = '/api/db/resources/user_model.csv'
CREATE_USER_PATH = '/api/v1/users/'
PRODUCTS_KITS_PATH = '/api/v1/products/kits/'
